### ISSUE TITLE
Create a Workflow suitable Docker container

### ISSUE THREAD

**Issue by johnbradley** [hdr-bgnn/drexel_metadata#7]
Create a docker container suitable for inclusion in a workflow for this repo that can be run on a single image that creates an output metadata file. Work has already been done on this in PR #6. I'm going to use this issue to document the changes related to creating the container so we can determine the minimal changes required to achieve this goal.

**Comment by johnbradley** [comment]
# Issue: `CUDA required`
When running `gen_metadata.py` on my laptop in a Docker container I received the following error:
```
Errored out (Torch not compiled with CUDA enabled)
```
I think this is due to the following code:
 https://github.com/hdr-bgnn/drexel_metadata/blob/a8720c3bfefcbd5caf7d948fad4ba90c2adc7f3c/gen_metadata.py#L43-L44
The `get_cfg()` function [defaults to using cuda](https://github.com/facebookresearch/detectron2/blob/2a1cec4c647dbe8a05f2d5b599d7d4c7cf9f04ad/detectron2/config/defaults.py#L32).

## Possible solution
The `mask_rcnn_R_50_FPN_3x.yaml` config file can be modified to use "cpu" instead of "cuda".
```
_BASE_: "Base-RCNN-FPN.yaml"
MODEL:
  WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-50.pkl"
  MASK_ON: True
  RESNETS:
    DEPTH: 50
  DEVICE: cpu
SOLVER:
  #STEPS: (210000, 250000)
  STEPS: (12300, 13500)
  MAX_ITER: 15000
```
